version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filemanager
    hostname: filemanager
    image: filemanager
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - filemanager

  mongodb:
    image: mongo:latest
    restart: on-failure
    container_name: mongodb
    user: root
    hostname: mongodb
    command: mongod --auth
    env_file:
      - .env
    environment:
      - MONGODB_DATABASE=filemanager
      - MONGODB_USERNAME=filemanager
      - MONGODB_PASSWORD=filepwd
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init-mongo.sh"]
    networks:
      - filemanager

networks:
  filemanager:
    driver: bridge